modLoader="javafml"
loaderVersion="[4,)"
license="${license}"
issueTrackerURL="${issue_tracker}"

[[mods]]
modId="${mod_id}"
version="${version}"
displayName="${mod_name}"
authors="${mod_author}"
description='''${mod_description}'''
logoFile="diet_icon.png"

[[dependencies.diet]]
modId="neoforge"
type="required"
versionRange="[21.0,22.0)"
ordering="NONE"
side="BOTH"

[[dependencies.diet]]
modId="minecraft"
type="required"
versionRange="[1.21,1.22)"
ordering="NONE"
side="BOTH"

[[dependencies.diet]]
modId="spectrelib"
type="required"
versionRange="[0.17.2,0.18)"
ordering="AFTER"
side="BOTH"